# 应用服务 WEB 访问端口
server:
  port: 8099
  servlet:
    context-path: /dv

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.188.137:3306/ding_video?serverTimezoneUTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Dase1101
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    database: 0
    host: 101.132.188.137
    port: 6380
    password: '000415'
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
  data:
    mongodb:
      uri: mongodb://tamiflu233:Dase1101@101.132.188.137:27017/ding_video